[tool.pytest.ini_options]
# Регистрируем маркеры, чтобы избежать ворнингов
markers = [
    "smoke: Критические тесты для быстрой проверки",
    "ui e2e: Медленные тесты, которые не хочется гонять постоянно",
    "api: Тесты, требующие внешних сервисов (БД, API)",
]